run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - typecheck

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
